[package]
name = "lyserver_media_plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
lyserver_plugin_wasm_runtime = { path = "../lyserver_plugin_wasm_runtime" }